In [8]:
import numpy as np

In [ ]:
# numpy
# 공학, 수학 대수학을 처리하는 용도로 사용
#  수치계산
#  scalar, vector, matrix, tensor...

## array

In [4]:
# list : [1,2,3,4,'a','b']
# string : "hello python"

L = [1,4,5,7]

test_arr = np.array(L)       # 리스트와 유사...
test_arr

array([1, 4, 5, 7])

In [5]:
test_arr[1]  #indexing

4

In [6]:
test_arr[1:3]  #slicing

array([4, 5])

In [7]:
type(test_arr)

numpy.ndarray

In [8]:
test_arr.shape    # 원소가 4개인 1차원 array => vector

(4,)

In [11]:
L = [1,2,3,'python']   # 리스트에서는 가능

In [12]:
np.array(L) # 모든 원소가 동일한 데이터 타이브로 구성 => 연산 속도가 높다

array(['1', '2', '3', 'python'], dtype='<U11')

In [14]:
L = [1,2,3,4, 3.14]
np.array(L)

array([1.  , 2.  , 3.  , 4.  , 3.14])

In [49]:
L = [[1,2,3,4,5], [4,5,6,7,8], [8,9,6,4,6]]
L

[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [8, 9, 6, 4, 6]]

In [50]:
np.array(L)    # matrix(행열)               

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [8, 9, 6, 4, 6]])

In [51]:
np.array(L).shape  # 2차원 metrix

(3, 5)

In [6]:
np.array(L).ndim             ### ndim????? 차원갯수

2

In [7]:
t = [[1,2,3,4,5], [4,5,6,7,8], [8,9,6,4,7]], [[1,2,3,4,5], [4,5,6,7,8], [8,9,6,4,7]]

t

([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [8, 9, 6, 4, 7]],
 [[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [8, 9, 6, 4, 7]])

In [8]:
np.array(t)  # 3차원 tensor

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [8, 9, 6, 4, 7]],

       [[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [8, 9, 6, 4, 7]]])

In [9]:
np.array(t).shape

(2, 3, 5)

In [ ]:
# reshape

In [10]:
L = [[1,2,3,4,5], [4,5,6,7,9]]
L

[[1, 2, 3, 4, 5], [4, 5, 6, 7, 9]]

In [11]:
test_mat = np.array(L)
test_mat

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 9]])

In [12]:
test_mat.shape

(2, 5)

In [13]:
test_mat.reshape(5,2)   # matrix

array([[1, 2],
       [3, 4],
       [5, 4],
       [5, 6],
       [7, 9]])

In [14]:
test_mat.reshape(10)     # vector

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 9])

In [15]:
test_mat.reshape(2,5,1)   # tensor

array([[[1],
        [2],
        [3],
        [4],
        [5]],

       [[4],
        [5],
        [6],
        [7],
        [9]]])

In [ ]:
test_mat.reshape(4, 3)     # 에러 원소의 갯수와 다른 shape으로 reshape은 불가능

In [ ]:
# np.array() : array로 형변환, datatype을 지정할 수 있다.

In [17]:
L = [[1,2,3,4,5], [4,5,6,7,9]]
np.array(L, float)

array([[1., 2., 3., 4., 5.],
       [4., 5., 6., 7., 9.]])

In [19]:
L = [[1,2,3,4,5], [4,5,6,7,9]]
np.array(L, str)

array([['1', '2', '3', '4', '5'],
       ['4', '5', '6', '7', '9']], dtype='<U1')

In [ ]:
# indexing

In [20]:
tm = np.array(L)
tm

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 9]])

In [ ]:
# arr[row_index, col_index]

In [21]:
tm[1,1]

5

In [22]:
tm[1][1]           # 판다스 문법에서는 쓰지 않음

5

In [23]:
tm

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 9]])

In [24]:
tm[0,2] = 10
tm

array([[ 1,  2, 10,  4,  5],
       [ 4,  5,  6,  7,  9]])

In [27]:
tm = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
tm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
tm[1, 2]

8

In [29]:
tm[0, 1:3]

array([2, 3])

In [30]:
tm[:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [31]:
tm[:, 1:4:2]

array([[2, 4],
       [7, 9]])

In [ ]:
# arange

In [32]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [33]:
list(np.arange(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [35]:
list(range(1,11, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [36]:
print(list(np.arange(1,11, 0.1)))

[1.0, 1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000004, 1.5000000000000004, 1.6000000000000005, 1.7000000000000006, 1.8000000000000007, 1.9000000000000008, 2.000000000000001, 2.100000000000001, 2.200000000000001, 2.300000000000001, 2.4000000000000012, 2.5000000000000013, 2.6000000000000014, 2.7000000000000015, 2.8000000000000016, 2.9000000000000017, 3.0000000000000018, 3.100000000000002, 3.200000000000002, 3.300000000000002, 3.400000000000002, 3.500000000000002, 3.6000000000000023, 3.7000000000000024, 3.8000000000000025, 3.9000000000000026, 4.000000000000003, 4.100000000000003, 4.200000000000003, 4.3000000000000025, 4.400000000000003, 4.5000000000000036, 4.600000000000003, 4.700000000000003, 4.800000000000003, 4.900000000000004, 5.0000000000000036, 5.100000000000003, 5.200000000000004, 5.300000000000004, 5.400000000000004, 5.5000000000000036, 5.600000000000004, 5.700000000000005, 5.800000000000004, 5.900000000000004, 6.000000000000004, 6.100000000000005, 6.20000000000000

In [37]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Operation

In [53]:
tm = np.arange(30).reshape(5,6)
tm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [54]:
tm.sum()

435

In [55]:
tm.mean()     # 평균함수

14.5

In [ ]:
#  (5,6)

In [56]:
tm.sum(axis=0)    # 세로끼리 연산

array([60, 65, 70, 75, 80, 85])

In [52]:
tm.sum(axis=1)     # 가로끼리 연산

array([ 15,  51,  87, 123, 159])

In [42]:
tm.max(axis=0)

array([24, 25, 26, 27, 28, 29])

In [43]:
tm.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [44]:
tm.min(axis=1)

array([ 0,  6, 12, 18, 24])

In [41]:
tm.std(axis=0)             ### std???  구글링 표준편차

array([8.48528137, 8.48528137, 8.48528137, 8.48528137, 8.48528137,
       8.48528137])

In [ ]:
# element wise peration : 원소간 연산

In [42]:
arr_a = np.arange(6).reshape(2,3)
arr_b = np.arange(6).reshape(2,3)

In [43]:
arr_a

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
arr_b

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
arr_a + arr_b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [53]:
arr_a - arr_b

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
arr_a * arr_b

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [55]:
arr_a == arr_b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Braodcasting
# shape이 서로 다른 array 간에 연산을 하는 경우, shape이 작은 array의 shape이 확장이 되어서
# element 간에 연산을 하게 된다

In [56]:
arr_a + 10          # scalar 가 2by3 matrix로 확장되어서 element wise 연산을 한다

array([[10, 11, 12],
       [13, 14, 15]])

In [60]:
arr_a

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
arr_a
arr_v = np.array([1,2,4])
arr_v

array([1, 2, 4])

In [61]:
arr_a + arr_v    # element간에 연산

array([[1, 3, 6],
       [4, 6, 9]])

In [ ]:
# Boolean Indexing
# array에 boolean array를 index로 하여 True에 해당하는 갑산을 추춤
# array의 길이와 boolean array의 길이가 같아야 한다

In [62]:
ta = np.array([1,2,3,4,3,5,6])

In [ ]:
# ta에서 5 이상인 값만 출력하시오

In [63]:
ta >= 5

array([False, False, False, False, False,  True,  True])

In [64]:
ta[ta >= 5]        # 별표

array([5, 6])

In [ ]:
# ta에서 짝수만 출력

In [65]:
ta[ta%2==0]

array([2, 4, 6])

In [ ]:
# 1 ~ 100 사이의 정수에서 20 보다 크고 30 보다 작은 3의 배수를 출력하시오
# => boolean indexing을 사용

In [81]:
t = np.arange(100)
t[30>t>20]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
test_arr = np.arange(1,101)
test_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [86]:
test_arr >20

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [87]:
test_arr < 30

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [88]:
test_arr%3==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [89]:
(test_arr >20) & (test_arr < 30) & (test_arr%3==0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [90]:
test_arr[(test_arr >20) & (test_arr < 30) & (test_arr%3==0)]

array([21, 24, 27])