* hidden_state => vector 
* vector size(hidden state size == cell size) : hyper parameter => 처음부터 끝까지 고정 ()

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Bidirectional

In [35]:
train_x = [
    [0.1, 4.2, 1.5, 1.1, 2.8],
    [1.0, 2.3, 2.4, 1.5, 3.1],
    [1.2, 2.1, 3.2, 2.2, 1.0],
    [0.2, 0.3, 1.2, 1.3, 2.0]
]
train_x

[[0.1, 4.2, 1.5, 1.1, 2.8],
 [1.0, 2.3, 2.4, 1.5, 3.1],
 [1.2, 2.1, 3.2, 2.2, 1.0],
 [0.2, 0.3, 1.2, 1.3, 2.0]]

In [36]:
np.array(train_x).shape

(4, 5)

In [37]:
train_x = np.array(train_x).reshape(1,4,5)

In [31]:
train_x = train_x.reshape(1, 4, 5)

AttributeError: 'tuple' object has no attribute 'reshape'

In [12]:
train_z = [[
    [0.1, 4.2, 1.5, 1.1, 2.8],
    [1.0, 2.3, 2.4, 1.5, 3.1],
    [1.2, 2.1, 3.2, 2.2, 1.0],
    [0.2, 0.3, 1.2, 1.3, 2.0]
],
[
    [0.1, 4.2, 1.5, 1.1, 2.8],
    [1.0, 2.3, 2.4, 1.5, 3.1],
    [1.2, 2.1, 3.2, 2.2, 1.0],
    [0.2, 0.3, 1.2, 1.3, 2.0]
]]

train_z

[[[0.1, 4.2, 1.5, 1.1, 2.8],
  [1.0, 2.3, 2.4, 1.5, 3.1],
  [1.2, 2.1, 3.2, 2.2, 1.0],
  [0.2, 0.3, 1.2, 1.3, 2.0]],
 [[0.1, 4.2, 1.5, 1.1, 2.8],
  [1.0, 2.3, 2.4, 1.5, 3.1],
  [1.2, 2.1, 3.2, 2.2, 1.0],
  [0.2, 0.3, 1.2, 1.3, 2.0]]]

In [13]:
np.array(train_z).shape

(2, 4, 5)

# RNN

In [38]:
# [[v,v,v,v,v], [v,v,v,v,v], [v,v,v,v,v], [v,v,v,v,v]]

hidden_state_size = 3

rnn = SimpleRNN(hidden_state_size, input_shape=(4,5), return_sequences=True, return_state=True)  # input_shape = (seq_len, input_dim) 
output_1, output_2 = rnn(train_x)    # return_sequences : cell마다 출력

print(output_1)  # last rnn cell의 hidden state 값
print(output_2)   # return_state=True 마지막 셀 하나만 추가로 출력

tf.Tensor(
[[[-0.46384576  0.97909683 -0.7930667 ]
  [-0.75040984  0.83308566 -0.90643466]
  [-0.9529137   0.9963711  -0.985934  ]
  [-0.47973564 -0.57756096 -0.79799247]]], shape=(1, 4, 3), dtype=float32)
tf.Tensor([[-0.47973564 -0.57756096 -0.79799247]], shape=(1, 3), dtype=float32)


In [39]:
hidden_state_size = 3

rnn = SimpleRNN(hidden_state_size, input_shape=(4,5), return_sequences=False, return_state=True) 
output_1, output_2 = rnn(train_x)    # return_sequences : cell마다 출력

print(output_1)  
print(output_2)   # return_state=True 마지막 셀 hidden state 하나만 추가로 출력

tf.Tensor([[-0.84280616  0.9958102   0.92853606]], shape=(1, 3), dtype=float32)
tf.Tensor([[-0.84280616  0.9958102   0.92853606]], shape=(1, 3), dtype=float32)


# LSTM

In [40]:
lstm = LSTM(3)
output = lstm(train_x)

print(output) # 마지막 cell의 hidden state값만 출력

tf.Tensor([[-0.46412665 -0.03080952  0.18212292]], shape=(1, 3), dtype=float32)


In [41]:
lstm = LSTM(3, return_sequences=True)
output_1 = lstm(train_x)

print(output_1)  # 모든 cell의 hidden state값 출력

tf.Tensor(
[[[ 0.4170059  -0.06399667  0.04572804]
  [ 0.35205215 -0.13611773  0.22800967]
  [ 0.13903649 -0.2954029   0.31841302]
  [ 0.10367267 -0.2872463   0.56054175]]], shape=(1, 4, 3), dtype=float32)


In [42]:
lstm = LSTM(3, return_state=True)
output_1 = lstm(train_x)

print(output_1)  # 마지막 cell의 hidden state와 cell state 모두 출력

[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.25126252, -0.17888656,  0.13996898]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.25126252, -0.17888656,  0.13996898]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.36384636, -1.253472  ,  0.3835483 ]], dtype=float32)>]


In [43]:
lstm = LSTM(3, return_state=True, return_sequences=True)
output_1, output_2, output_3 = lstm(train_x)

print(output_1)
print(output_2)
print(output_3)

tf.Tensor(
[[[ 0.04926966 -0.35227564 -0.0891728 ]
  [ 0.04716298 -0.51887715 -0.22069742]
  [ 0.05002563 -0.46418232 -0.25902894]
  [ 0.02019375 -0.50653327 -0.11088155]]], shape=(1, 4, 3), dtype=float32)
tf.Tensor([[ 0.02019375 -0.50653327 -0.11088155]], shape=(1, 3), dtype=float32)
tf.Tensor([[ 0.05328591 -1.1500757  -0.28571987]], shape=(1, 3), dtype=float32)


# bidirctional LSTM

In [44]:
bilstm = Bidirectional(LSTM(3))
hidden_states = bilstm(train_x)

print(hidden_states)    # 순방향과 역방향의 각 hidden을 붙여서 나옴

tf.Tensor([[ 0.26466647  0.27472836  0.02537536 -0.38774422  0.07090999 -0.20201066]], shape=(1, 6), dtype=float32)


In [45]:
bilstm = Bidirectional(LSTM(3, return_sequences=True))
hidden_states = bilstm(train_x)

print(hidden_states)  # 6차원 vector가 네개

tf.Tensor(
[[[-0.10360917  0.19707294  0.50094724  0.09079915 -0.06341184
   -0.54574203]
  [-0.235489    0.42606142  0.6431751   0.1291828  -0.09211893
   -0.2268604 ]
  [-0.24305855  0.50146407  0.49337417  0.17004019 -0.16561075
   -0.20592453]
  [-0.3043269   0.48852888  0.5235814   0.09982269 -0.08658082
   -0.13718887]]], shape=(1, 4, 6), dtype=float32)


In [48]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True))
a, b, c, d, e = bilstm(train_x)

print(a)  # all cell hidden state
print(b)  # forward_h
print(c)  # forward_c
print(d)  # backward_h
print(e)  # backward_c

tf.Tensor(
[[[-0.02992779 -0.2986732   0.04278515 -0.02763343 -0.34024808
   -0.08105202]
  [-0.03548211 -0.30765766  0.5105621  -0.00817041 -0.40089157
   -0.04605862]
  [-0.03931694 -0.36916584  0.3250572   0.02248387 -0.12220442
    0.01486034]
  [-0.06850964 -0.18047965  0.44340712 -0.00955396 -0.18989304
    0.01204422]]], shape=(1, 4, 6), dtype=float32)
tf.Tensor([[-0.06850964 -0.18047965  0.44340712]], shape=(1, 3), dtype=float32)
tf.Tensor([[-0.28461754 -0.93275386  1.1591265 ]], shape=(1, 3), dtype=float32)
tf.Tensor([[-0.02763343 -0.34024808 -0.08105202]], shape=(1, 3), dtype=float32)
tf.Tensor([[-0.3975839  -1.6836963  -0.18196623]], shape=(1, 3), dtype=float32)
